//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Application.ResponseNotifications.ErrorResponses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResponseText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResponseText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballManager.Application.ResponseNotifications.ErrorResponses.ErrorResponseText", typeof(ErrorResponseText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applcation doesn&apos;t exist on the plaform..
        /// </summary>
        public static string ApplicationNotRegisteredOnThePlatform {
            get {
                return ResourceManager.GetString("ApplicationNotRegisteredOnThePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity doesn&apos;t exist..
        /// </summary>
        public static string EntityDoesntExist {
            get {
                return ResourceManager.GetString("EntityDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering the client applicaiton with the identity provider.
        /// </summary>
        public static string ErrorRegisteringClientApplication {
            get {
                return ResourceManager.GetString("ErrorRegisteringClientApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string GeneralUnhandled {
            get {
                return ResourceManager.GetString("GeneralUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your handle has already been chosen, please choose a different handle..
        /// </summary>
        public static string HandleIsNotUnique {
            get {
                return ResourceManager.GetString("HandleIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified message doesn&apos;t exist or has already been removed..
        /// </summary>
        public static string MessageDoesntExist {
            get {
                return ResourceManager.GetString("MessageDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist on the platform..
        /// </summary>
        public static string UserNotRegisteredOnThePlatform {
            get {
                return ResourceManager.GetString("UserNotRegisteredOnThePlatform", resourceCulture);
            }
        }
    }
}
